name: pub_server
version: 0.1.6-dev
author: Dart Team <misc@dartlang.org>
description: Re-usable components for creating a custom Dart package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  http_parser: ^4.0.2
  logging: ^1.2.0
  mime: ^1.0.4
  pub_semver: ^2.1.4
  shelf: ^1.4.1
  yaml: ^3.1.2

dev_dependencies:
  archive: ^3.4.9
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.5.1
  pedantic: ^1.2.0
  test: ^1.3.0
